ProjekatETaxi/ETaxiDotNet/ETaxiDotNet/Models/ProfilViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ETaxiDotNet.Models
{
    public class ProfilViewModel
    {
        [Required]
        [Display(Name = "Name")]
        public string Ime { get; set; }

        [Required]
        [Display(Name = "Surname")]
        public string Prezime { get; set; }

        [Required]
        [Display(Name = "Region")]
        public string Region { get; set; }

        [Required]
        [Display(Name = "Deliveries made")]
        public int BrojVoznji { get; set; }

        [Required]
        [Display(Name = "Rating")]
        public int Ocjena { get; set; }

        [Required]
        [Display(Name = "Car model")]
        public string ModelAuta { get; set; }

        [Required]
        [Display(Name = "Car link")]
        public string LinkAuta { get; set; }

        [Required]
        [Display(Name = "Status")]
        public string StanjeVozaca { get; set; }


    }
}

ProjekatETaxi/ETaxiDotNet/ETaxiDotNet/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
namespace OnlineVideotekaFenixASPNET.Controllers
{
    public class PhotoController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            Session["val"] = "";
            return View();
        }
        [HttpPost]
        public ActionResult Index(string Imagename)
        {
            ViewBag.pic = "http://localhost:51865/WebImages/" + Session["val"].ToString();
            return RedirectToAction("MyProfile", "Users", new { a = Session["val"].ToString() });
        }

        public JsonResult Rebind()
        {
            string path = "http://localhost:51865/WebImages/" + Session["val"].ToString();
            return Json(path, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Capture()
        {
            var stream = Request.InputStream;
            string dump;
            using (var reader = new StreamReader(stream))
            {
                dump = reader.ReadToEnd();
                DateTime nm = DateTime.Now;
                string date = nm.ToString("yyyymmddMMss");
                var path = Server.MapPath("~/WebImages/" + date + "test.jpg");
                System.IO.File.WriteAllBytes(path, String_To_Bytes2(dump));
                ViewData["path"] = date + "test.jpg";
                Session["val"] = date + "test.jpg";
            }
            return View("Index");
        }
        private byte[] String_To_Bytes2(string strInput)
        {
            int numBytes = (strInput.Length) / 2;
            byte[] bytes = new byte[numBytes];
            for (int x = 0; x < numBytes; ++x)
            {
                bytes[x] = Convert.ToByte(strInput.Substring(x * 2, 2), 16);
            }
            return bytes;
        }
    }
}

ProjekatETaxi/ETaxiDotNet/ETaxiDotNet/Controllers/ProfilController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ETaxiDotNet.Controllers
{
    public class ProfilController : Controller
    {
        // GET: Profil
        public ActionResult Profil()
        {
            return View();
        }
    }
}

ProjekatETaxi/ETaxiDotNet/ETaxiDotNet/Views/Profil/Profil.cshtml
@model ETaxiDotNet.Models.ProfilViewModel

@{
    ViewBag.Title = "Profil";
}

<h2>Profil</h2>
<div class="row">
    <div class="col-md-4">

        <section id="picture">
            <img src="../WebImages/profill.png" alt="Sample Image" width="400" height="400" />
            <br />
            <br />
            <div class="form-group">
                <div class="col-md-offset-4 col-md-8">
                    <input type="submit" value="Take a photo" onclick="location.href='@Url.Action("Index","Photo")'" class="btn btn-primary" />
                </div>
            </div>

        </section>
    </div>
    
    <div class="col-md-6">

        <section id="informations">

            <div class="form-group">
                @Html.LabelFor(m => m.Ime, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Ime, new { @class = "form-control" })
                </div>
            </div>
            <br />
            <br />

            <div class="form-group">
                @Html.LabelFor(m => m.Prezime, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Prezime, new { @class = "form-control" })
                </div>
            </div>
            <br />
            <br />

            <div class="form-group">
                @Html.LabelFor(m => m.Region, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.PasswordFor(m => m.Region, new { @class = "form-control" })
                </div>
            </div>
            <br />
            <br />

            <div class="form-group">
                @Html.LabelFor(m => m.BrojVoznji, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.BrojVoznji, new { @class = "form-control" })
                </div>
            </div>
            <br />
            <br />

            <div class="form-group">
                @Html.LabelFor(m => m.Ocjena, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Ocjena, new { @class = "form-control" })
                </div>
            </div>
            <br />
            <br />

            <div class="form-group">
                @Html.LabelFor(m => m.ModelAuta, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.ModelAuta, new { @class = "form-control" })
                </div>
            </div>

            <br />
            <br />
            <div class="form-group">
                @Html.LabelFor(m => m.LinkAuta, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.LinkAuta, new { @class = "form-control" })
                </div>
            </div>

            <br />
            <br />

            <div class="form-group">
                @Html.LabelFor(m => m.StanjeVozaca, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.StanjeVozaca, new { @class = "form-control" })
                </div>
            </div>

        </section>

    </div>


</div>

<br />
<br />